// Exercise 1.9

function inc(n) {
    return n + 1;
}

function dec(n) {
    return n - 1;
}

// Each of the following two functions defines a method for adding two positive integers in
// terms of the functions inc, which increments its argument by 1, and dec, which decrements
// its argument by 1.

// function plus(a, b) {
    // return a === 0 ? b : inc(plus(dec(a), b));
// }
// plus(4, 5);

function plus(a, b) {
    return a === 0 ? b : plus(dec(a), inc(b));
}
plus(4, 5);


// Using the substitution model, illustrate the process generated by each function in evaluating
// plus(4, 5);. Are these processes iterative or recursive?

// Both cases, processes are iterative